#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "constants.h"
#include "control.h"
#include "hillas.h"
#include "event.h"
#include "airshower.h"
#include "atmosphere-withdb.h"
#include "toolbox.h"
#include "nerling.h"

//#define CKV_HILLAS
#define CVPHASE_TRADITIONAL

/*
 * nerling.c
 *
 * This file contains the set of functions for modeling Cherenkov light 
 *   generated by an EAS as described by Nerling et al., in the paper 
 *   "Universality of electron distributions in high-energy air showers ---
 *   Description of Cherenkov light production", Astroparticle Physics, v24 
 *   2006, pp 421-437.
 *
 * Author: Sean R. Stratton
 *         Rutgers University, Dept. of Physics & Astronomy
 *
 * 10.20.08  :  Initial revision
 *
 */

/* Parameterization of the electron energy spectrum. */
/* for Ecut = 1MeV */
#if ( DEDX_MODEL == 1 ) || ( DEDX_MODEL == 5 ) || ( DEDX_MODEL == 6 ) || ( DEDX_MODEL == 14 ) || ( DEDX_MODEL == 15 ) || ( DEDX_MODEL == 13) || (DEDX_MODEL == 12) || ( DEDX_MODEL == 16)
#define NERLING_A0K0         1.45098e-01
#define NERLING_A0K1         6.20114e+00
#define NERLING_A0K2        -5.96851e-01
#elif ( DEDX_MODEL == 2 ) || ( DEDX_MODEL == 3 ) || ( DEDX_MODEL == 4 )
/* for Ecut = 0.1 MeV (AZech Shower lib) */
#define NERLING_A0K0         1.42049e-01
#define NERLING_A0K1         6.18075e+00
#define NERLING_A0K2        -6.05484e-01
#endif

#define NERLING_A1A          6.42522e+00
#define NERLING_A1B          1.53183e+00
#define NERLING_A2A          1.68168e+02
#define NERLING_A2B          4.21368e+01

/* Parameterization of the Cherenkov light phase function */
#define NERLING_A0           4.2489e-01
#define NERLING_A1           5.8371e-01
#define NERLING_A2          -8.2373e-02

#define NERLING_B0           5.5108e-02
#define NERLING_B1          -9.5587e-02
#define NERLING_B2           5.6952e-02

#define NERLING_ALPHA        0.62694
#define NERLING_BETA         0.60590
#define NERLING_ALPHA_PRIME 10.509
#define NERLING_BETA_PRIME  -4.9644

/* Parameterization of ionization loss rate */
#if ( DEDX_MODEL == 1 )
/* empirical parameters given in Nerling et. al (1, 100, 100) */
#define NERLING_C1           3.90883
#define NERLING_C2           1.05301
#define NERLING_C3           9.91717
#define NERLING_C4           2.41715
#define NERLING_C5           0.13180

#elif ( DEDX_MODEL == 2 )
/* GH (Gareth's) parameters for (0.1, 50, 50) */
#define NERLING_C1           3.41500
#define NERLING_C2           1.28531
#define NERLING_C3           5.04560
#define NERLING_C4           2.22184
#define NERLING_C5           0.23215

#elif ( DEDX_MODEL == 3 )
/* GH (Gareth's) parameters for (0.1, 300, 700) */
#define NERLING_C1           0.82053
#define NERLING_C2           0.77152
#define NERLING_C3           8.40829
#define NERLING_C4           2.41826
#define NERLING_C5           0.09848

#elif ( DEDX_MODEL == 4 )
/* DRB's fit to alpha_eff from Integrals of modified Nerling fe above 0.1 MeV */
#define NERLING_C1           0.1550
#define NERLING_C2           0.2621
#define NERLING_C3           1.240
#define NERLING_C4           2.145
#define NERLING_C5           -0.02735

#elif ( DEDX_MODEL == 5 )
/* DRB's fit to alpha_eff from integrals of modified Nerling fe above 1 MeV */
#define NERLING_C1           0.2276
#define NERLING_C2           0.5706
#define NERLING_C3           2.140
#define NERLING_C4           2.207
#define NERLING_C5           0.1234

#elif ( DEDX_MODEL == 6 )
/* SS's fit to alpha_eff from integrals of modified Nerling fe above 1 MeV */
#define NERLING_C1           1.1150
#define NERLING_C2           1.0869
#define NERLING_C3           1.3191
#define NERLING_C4           1.7858
#define NERLING_C5           0.17499

#elif ( DEDX_MODEL == 14 )
/* TAS's fit to alpha_eff from QGSJet01c protons+iron 20150206 */
#define NERLING_C1              159.899
#define NERLING_C2              1.63203
#define NERLING_C3              9.99531
#define NERLING_C4              2.36229
#define NERLING_C5              0.193587

#elif ( DEDX_MODEL == 15 )
/* TAS's fit (20150220) for QGSJet II-04 protons+iron */
#define NERLING_C1              390.457
#define NERLING_C2              1.69574
#define NERLING_C3              10.8641
#define NERLING_C4              2.36977
#define NERLING_C5              0.188803

#elif ( DEDX_MODEL == 13 )
/* TAS's fit (20150227) for QGSJet II-03 proton+iron */
#define NERLING_C1              337.164
#define NERLING_C2              1.66721
#define NERLING_C3              10.9392
#define NERLING_C4              2.36865
#define NERLING_C5              0.189572

#elif ( DEDX_MODEL == 12 )
/* TAS's fit for EPOS-LHC protons+iron */
#define NERLING_C1              129.249
#define NERLING_C2              1.60964
#define NERLING_C3              9.79053
#define NERLING_C4              2.35824
#define NERLING_C5              0.199557

#elif ( DEDX_MODEL == 16 )
/* TAS's fit for SIBYLL 2.1 protons+iron */
#define NERLING_C1              0.525561
#define NERLING_C2              0.865884
#define NERLING_C3              6.07073
#define NERLING_C4              2.35392
#define NERLING_C5              0.199020


#else
/* Force alpha eff. to evaluate to a constant '2.4' MeV/g/cm^2 */
#define NERLING_C1           0.00
#define NERLING_C2           0.00
#define NERLING_C3           0.00
#define NERLING_C4           2.40
#define NERLING_C5           0.00

#endif

/*
 * Computes the ionization loss rate at shower age 's'.
 *
 * Input:
 *   double s - shower age ( 3/(1+2 Xmax/X) )
 *
 * Returns: 
 *   Ionization loss rate at 's' in eV/(g/cm^2).
 */
double getAlphaEff(double s) {
  double alpha;
  alpha = NERLING_C1/pow((NERLING_C2+s),NERLING_C3)+NERLING_C4+NERLING_C5*s;
  return alpha * 1.0e+6;  /* convert to eV before returning */
}

/*
 * Computes the differential electron spectrum.
 *
 * Inputs:
 *   double s - shower age ( 3/(1+2 Xmax/X) )
 *   double e - electron energy ( eV )
 *
 * Returns:
 *   The normalized differential energy for an electron with energy 'e' 
 *     corresponding to shower age 's', i.e.
 *
 *          f_e(s,E) = \frac{1}{N_e} \frac{dN_e}{d \ln{E}}
 *
 */
double getDifferentialElectronSpectrum(double s, double e) {
  double a, b, c;

  e *= 1.0e-6;  /* convert E to MeV */

  /* a = a_0 E */
  a = e * NERLING_A0K0 * exp(NERLING_A0K1*s + NERLING_A0K2*s*s);

  /* b = E + a_1 */
  b = e + NERLING_A1A - NERLING_A1B*s;

  /* c = E + a_2 */
  c = e + NERLING_A2A - NERLING_A2B*s;

  return a * pow(c,-s) / b;
}

/* This static function is meant to passed to an integrator */
static double sCv;
static double delCv;
static double cvIntegrand(double logE) {
  double E = pow(10.,logE);
  double f = getDifferentialElectronSpectrum(sCv,E);
  double y = 2.0*delCv - (ELECTRON_MASS*ELECTRON_MASS)/(E*E);
  return y*f;
}

/*
 * Computes the number of Cherenkov photons produced per radiation length X.  
 *
 * Inputs:
 *   int season - one of SPRING, SUMMER, FALL, or WINTER.
 *   double s - shower age (3/(1+2*Xmax/X))
 *   double h - altitude in meters above sea level
 *   double dl - segment length in meters
 *
 * Output:
 *   double dncv - The (normalized) number of Cherenkov photons generated per 
 *     radiation length at shower age 's' and altitude 'h', i.e.
 *
 *      \frac{1}{N_{\mathrm{ch}}} \frac{dN_{\gamma}}{dX}(s, h)
 *
 */
//void getCvPhotonIncrRate(int season, double s, double h, double dl, double *dncv) {
void getCvPhotonIncrRate(fdatmos_param_dst_common *season,
			 double s, double h, double *dncv) {
  int i, j, idx, num;
  double en, cki;
  double wl, rho, press, temp, delta;
  static int initialized = FALSE;
  static double cvspectrum[NWAVELEN_BANDS]; 
  double mcru_wla, mcru_wlb;

  double mcru_fnu[16] = {11., 11., 10., 10., 9.0, 8.5, 8.1, 7.7,
                         7.3, 6.9, 6.6, 6.3, 6.0, 5.7, 5.5, 5.2};
  static double fnu[NWAVELEN_BANDS];

  if ( ! initialized ) {
    /*
     * Calculate the integral of 2PiAlpha/lambda^2 between wl values, in
     * units of 1/cm
     */
    wl = LAMBDA0;
    for ( i=0; i<NWAVELEN_BANDS; i++ ) {
      cvspectrum[i] = TWO_PI_ALPHA / wl;
      wl += DLAMBDA;
      cvspectrum[i] -= TWO_PI_ALPHA / wl;
      cvspectrum[i] /= 100.;

      fnu[i] = 0.;
    }

    /*
     * Dividing mcru's fnu (Cerenkov spectrum) into
     * NWAVELEN_BANDS.
     */
    num = (int)(NWAVELEN_BANDS * DLAMBDA*1.0e9);
    for ( i=0; i<num; i++ ) {
      wl = LAMBDA0*1.0e9 + (double)i;
      idx = i / (int)(DLAMBDA*1.0e9);
      for ( j=0; j<16; j++ ) {
        mcru_wla = 280. + 9.0 * (double)j;
        mcru_wlb = 280. + 9.0 * (double)(j+1);
        if (mcru_wla > wl)
          break;
        else if (wl >= mcru_wla && wl < mcru_wlb)
          fnu[idx] += mcru_fnu[j] / 9.0;
      }
    }

    initialized = TRUE;
  }

  rho = getDensityByAltitude(season, h);

  press = getPressureByAltitude(season, h);
  temp = getTemperatureByAltitude(season, h);
  delta = getDeltaByPressTemp(press, temp);

  /*
   * Perform the integral part of ansatz (5), starting at the
   * threshold E
   */ 
  en = ELECTRON_MASS / sqrt( 2.0 * delta );

#ifdef CKV_HILLAS
  double Elo, Ehi, dE;
  double E1, E2, s1, s2;
  double gfc, tint;
  int nbin;
  
  Elo = en;
  Ehi = 4.0 * Elo;

  cki = getHillasIntegrand (Elo, s, delta);

  nbin = 5;
  dE = (Ehi - Elo) / (double)nbin;

  /* Integrate to find fraction of electrons above threshold (?) */
  for (i=0; i<nbin; i++) {
    E1 = Elo + dE * ((double)i + 0.5);	// midpoint of interval
    E2 = E1 + dE / 2.0;			// endpoint of interval

    s1 = 4.0 * getHillasIntegrand (E1, s, delta);
    s2 = 2.0 * getHillasIntegrand (E2, s, delta);

    cki += s1 + s2;
  }

  /* mcru's simshw.f "tint" (in MeV) */
  tint = (dE *1.0e-6) * (cki - s2/2.0) / 6.0;

  /* mcru's cherltp.f "gfc" */
  gfc = tint + 2.0 * getHillasT(Ehi, s) * delta;

  /* mcru's great 458.6 - anyone have a clue? */
  for ( i=0; i<NWAVELEN_BANDS; i++ )
    dncv[i] = 458.6 * fnu[i] * gfc * dl;
#else

  sCv = s;
  delCv = delta;
  double lE0 = log10(en);
  // Do the integral cki = Integral_lE0^(lE0+4)[f*y*dlE]
  if (sCv>0. && sCv<=3.)
    cki = LN10*qsimp(cvIntegrand,lE0,lE0+4.,1.0e-4);
  else
    cki = 0.;

  for ( i=0; i<NWAVELEN_BANDS; i++ )
    dncv[i] = cki * cvspectrum[i] / rho;

#endif
}

/*
 * Computes the angular dependence of produced Cherenkov light, according to 
 *   eq. (21).
 *
 * Inputs:
 *   int season - any one of SPRING, SUMMER, FALL, or WINTER.
 *   double s - shower age ( 3/(1+2 Xmax/X) )
 *   double h - altitude in meters above sea level.
 *   double q - angle from shower axis in radians.
 *
 * Returns:
 *   The fraction of Cherenkov photons directed at angle 'q' from the shower 
 *     axis, normalized so that
 *
 *               \int_0^\pi A_\gamma(\theta, h, s) = 2*pi
 *
 */
//double cvPhaseFunction(int season, double s, double h, double q) {
double cvPhaseFunction(fdatmos_param_dst_common *season,
		       double s, double h, double q) {

  double delta, eth, qc, pf;
  double press = getPressureByAltitude(season, h);
  double temp = getTemperatureByAltitude(season, h);
  delta = getDeltaByPressTemp(press, temp);
  eth = ELECTRON_MASS / sqrt( 2.0 * delta );
  eth *= 1.0e-6;  /* convert to MeV */

#ifdef CVPHASE_TRADITIONAL

  /* Traditional approximation for calculating Cerenkov
   * contamination (page 431-432 in Nerling, equation 11).
   */
  s = s;
  qc = 0.83 * pow(eth, -0.67);
  pf = exp (-q / qc) / qc;

#else

  double a = NERLING_A0 + NERLING_A1*s + NERLING_A2*s*s;
  double b = NERLING_B0 + NERLING_B1*s + NERLING_B2*s*s;
  double pf_a, pf_b;

  qc = NERLING_ALPHA*pow(eth, -NERLING_BETA);
  double qcc = ( NERLING_ALPHA_PRIME + NERLING_BETA_PRIME*s ) * qc;

  /* if qc or qcc is <= 0.0, pf blows up! */
  if (qc > 0.)
    pf_a = a*exp(-q/qc)/qc;
  else
    pf_a = 0.;

  if (qcc > 0.)
    pf_b = b*exp(-q/qcc)/qcc;
  else
    pf_b = 0.;

  /* pf = a*exp(-q/qc)/qc + b*exp(-q/qcc)/qcc; */
  pf = pf_a + pf_b;
  //  pf /= 2.0 * M_PI;  /* divide out the annulus */

#endif

  pf /= 2.0 * M_PI * sin(q);
  return pf;
}
